USE steam;

DROP TABLE IF EXISTS `users`;
CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(12) NOT NULL UNIQUE,
	email VARCHAR(60) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	first_name VARCHAR(12) NOT NULL,
	last_name VARCHAR(12) NOT NULL
	admin INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE sessions (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL UNIQUE,
	token VARCHAR(12) NOT NULL UNIQUE,
	lastupdate TIMESTAMP DEFAULT NOW()
);